sudo: required

git:
  depth: 1

branches:
  only:
    - master

services:
  - docker

before_install:
  - make build

script:
  - make test

after_success:
  export TAG=`git name-rev --tags --name-only $(git rev-parse ${TRAVIS_COMMIT::8})`
  if [ "$TAG" != "undefined" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="${DOCKER_PASSWORD}"
    make push
  fi
